<a href="https://colab.research.google.com/github/akhythmetic/EDUCLASH/blob/main/Educlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ÉDUCATION : *Bellum Lycei Privati et Publici*

### Installation de paquets

In [2]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)

### Importation de librairie

In [7]:
import requests
import pandas as pd

### Récupération des données des lycées

Dans cette cellule, nous récupérons via une API les données intitulées **"Indicateurs de valeur ajoutée des lycées d'enseignement général et technologique (ancien)"**. Ces données nous serviront à analyser les performances des lycées publics et privés sous contrat.

In [6]:
url_lycee_ancien = "https://data.education.gouv.fr/api/explore/v2.1/catalog/datasets/fr-en-indicateurs-de-resultat-des-lycees-denseignement-general-et-technologique/records?limit=20"
response = requests.get(url_lycee_ancien)

if response.status_code == 200:
    dico_lycee_ancien = response.json()
    print(dico_lycee_ancien)
else:
    print("Erreur lors de la récupération des données")

{'total_count': 27808, 'results': [{'etablissement': 'LYCEE PAUL PAINLEVE (GENERAL ET TECHNO.)', 'annee': '2023', 'ville': 'OYONNAX', 'code_etablissement': '0010034G', 'commune': '01283', 'academie': 'LYON', 'departement': 'AIN', 'secteur_public_pu_prive_pr': 'public', 'effectif_presents_serie_l': None, 'effectif_presents_serie_es': None, 'effectif_presents_serie_s': None, 'effectif_presents_serie_stg': None, 'effectif_presents_serie_sti2d': None, 'effectif_presents_serie_std2a': None, 'effectif_presents_serie_stmg': 67, 'effectif_presents_serie_sti': None, 'effectif_presents_serie_stl': None, 'effectif_presents_serie_st2s': 28, 'effectif_presents_serie_musiq_danse': None, 'effectif_presents_serie_hotellerie': None, 'effectif_presents_total_series': 161, 'taux_brut_de_reussite_serie_l': None, 'taux_brut_de_reussite_serie_es': None, 'taux_brut_de_reussite_serie_s': None, 'taux_brut_de_reussite_serie_stg': None, 'taux_brut_de_reussite_serie_sti2d': None, 'taux_brut_de_reussite_serie_std2a': None, 'taux_brut_de_reussite_serie_stmg': '91', 'taux_brut_de_reussite_serie_sti': None, 'taux_brut_de_reussite_serie_stl': None, 'taux_brut_de_reussite_serie_st2s': '100', 'taux_brut_de_reussite_serie_musiq_danse': None, 'taux_brut_de_reussite_serie_hotellerie': None, 'taux_brut_de_reussite_total_series': 91.0, 'taux_reussite_attendu_acad_serie_l': None, 'taux_reussite_attendu_acad_serie_es': None, 'taux_reussite_attendu_acad_serie_s': None, 'taux_reussite_attendu_acad_serie_stg': None, 'taux_reussite_attendu_acad_serie_sti2d': None, 'taux_reussite_attendu_acad_serie_std2a': None, 'taux_reussite_attendu_acad_serie_stmg': None, 'taux_reussite_attendu_acad_serie_sti': None, 'taux_reussite_attendu_acad_serie_stl': None, 'taux_reussite_attendu_acad_serie_st2s': None, 'taux_reussite_attendu_acad_serie_musiq_danse': None, 'taux_reussite_attendu_acad_serie_hotellerie': None, 'taux_reussite_attendu_acad_total_series': None, 'taux_reussite_attendu_france_serie_l': None, 'taux_reussite_attendu_france_serie_es': None, 'taux_reussite_attendu_france_serie_s': None, 'taux_reussite_attendu_france_serie_stg': None, 'taux_reussite_attendu_france_serie_sti2d': None, 'taux_reussite_attendu_france_serie_std2a': None, 'taux_reussite_attendu_france_serie_stmg': None, 'taux_reussite_attendu_france_serie_sti': None, 'taux_reussite_attendu_france_serie_stl': None, 'taux_reussite_attendu_france_serie_st2s': None, 'taux_reussite_attendu_france_serie_musiq_danse': None, 'taux_reussite_attendu_france_serie_hotellerie': None, 'taux_reussite_attendu_france_total_series': None, 'taux_mention_brut_serie_l': None, 'taux_mention_brut_serie_es': None, 'taux_mention_brut_serie_s': None, 'taux_mention_brut_serie_sti2d': None, 'taux_mention_brut_serie_std2a': None, 'taux_mention_brut_serie_stmg': '22', 'taux_mention_brut_serie_stl': None, 'taux_mention_brut_serie_st2s': '46', 'taux_mention_brut_serie_musiq_danse': None, 'taux_mention_brut_serie_hotellerie': None, 'taux_mention_brut_toutes_series': 37.0, 'taux_mention_attendu_serie_l': None, 'taux_mention_attendu_serie_es': None, 'taux_mention_attendu_serie_s': None, 'taux_mention_attendu_serie_sti2d': None, 'taux_mention_attendu_serie_std2a': None, 'taux_mention_attendu_serie_stmg': None, 'taux_mention_attendu_serie_stl': None, 'taux_mention_attendu_serie_st2s': None, 'taux_mention_attendu_serie_musiq_danse': None, 'taux_mention_attendu_serie_hotellerie': None, 'taux_mention_attendu_toutes_series': None, 'sructure_pedagogique_en_5_groupes': None, 'sructure_pedagogique_en_7_groupes': None, 'pourcentage_bacheliers_sortants_2de_1re_term_etab': None, 'pourcentage_bacheliers_sortants_terminales_etab': None, 'pourcentage_bacheliers_sortants_2de_1re_term_acad': None, 'pourcentage_bacheliers_sortants_terminales_acad': None, 'pourcentage_bacheliers_sortants_2de_1re_term_france': None, 'pourcentage_bacheliers_sortants_terminales_france': None, 'effectif_de_seconde': 104, 'effectif_de_premiere': 181, 'effectif_de_terminale': 213, 'taux_acces_brut_seconde_bac': 77.0, 'taux_acces_attendu_acad_seconde_bac': None, 'taux_acces_attendu_france_seconde_bac': None, 'taux_acces_brut_premiere_bac': '92', 'taux_acces_attendu_acad_premiere_bac': None, 'taux_acces_attendu_france_premiere_bac': None, 'taux_acces_brut_terminale_bac': '95', 'taux_acces_attendu_france_terminale_bac': None, 'libelle_region_2016': 'AUVERGNE-RHONE-ALPES', 'code_region_2016': '84', 'code_departement': '01', 'libelle_departement': 'Ain', 'va_reu_total': '0', 'va_acc_seconde': '-4', 'va_men_total': '-5', 'va_reu_l': None, 'va_reu_es': None, 'va_reu_s': None, 'va_reu_stg': None, 'va_reu_sti2d': None, 'va_reu_std2a': None, 'va_reu_stmg': '5', 'va_reu_sti': None, 'va_reu_stl': None, 'va_reu_st2s': '6', 'va_reu_musiq_danse': None, 'va_reu_hotellerie': None, 'va_acc_premiere': '2', 'va_acc_terminale': '2', 'va_men_l': None, 'va_men_es': None, 'va_men_s': None, 'va_men_sti2d': None, 'va_men_std2a': None, 'va_men_stmg': '-5', 'va_men_stl': None, 'va_men_st2s': '0', 'va_men_musiq_danse': None, 'va_men_hotellerie': None, 'presents_gnle': 66.0, 'taux_reu_brut_gnle': '86', 'va_reu_gnle': '-8', 'taux_men_brut_gnle': '48', 'va_men_gnle': '-8', 'nombre_de_mentions_tb_avec_felicitations_g': None, 'nombre_de_mentions_tb_sans_felicitations_g': 6, 'nombre_de_mentions_b_g': 9, 'nombre_de_mentions_ab_g': 17, 'nombre_de_mentions_tb_avec_felicitations_t': None, 'nombre_de_mentions_tb_sans_felicitations_t': 1, 'nombre_de_mentions_b_t': 6, 'nombre_de_mentions_ab_t': 21}, {'etablissement': 'LYCEE DE LA COTIERE', 'annee': '2023', 'ville': 'LA BOISSE', 'code_etablissement': '0011326L', 'commune': '01049', 'academie': 'LYON', 'departement': 'AIN', 'secteur_public_pu_prive_pr': 'public', 'effectif_presents_serie_l': None, 'effectif_presents_serie_es': None, 'effectif_presents_serie_s': None, 'effectif_presents_serie_stg': None, 'effectif_presents_serie_sti2d': None, 'effectif_presents_serie_std2a': None, 'effectif_presents_serie_stmg': 68, 'effectif_presents_serie_sti': None, 'effectif_presents_serie_stl': None, 'effectif_presents_serie_st2s': None, 'effectif_presents_serie_musiq_danse': None, 'effectif_presents_serie_hotellerie': None, 'effectif_presents_total_series': 383, 'taux_brut_de_reussite_serie_l': None, 'taux_brut_de_reussite_serie_es': None, 'taux_brut_de_reussite_serie_s': None, 'taux_brut_de_reussite_serie_stg': None, 'taux_brut_de_reussite_serie_sti2d': None, 'taux_brut_de_reussite_serie_std2a': None, 'taux_brut_de_reussite_serie_stmg': '96', 'taux_brut_de_reussite_serie_sti': None, 'taux_brut_de_reussite_serie_stl': None, 'taux_brut_de_reussite_serie_st2s': None, 'taux_brut_de_reussite_serie_musiq_danse': None, 'taux_brut_de_reussite_serie_hotellerie': None, 'taux_brut_de_reussite_total_series': 96.0, 'taux_reussite_attendu_acad_serie_l': None, 'taux_reussite_attendu_acad_serie_es': None, 'taux_reussite_attendu_acad_serie_s': None, 'taux_reussite_attendu_acad_serie_stg': None, 'taux_reussite_attendu_acad_serie_sti2d': None, 'taux_reussite_attendu_acad_serie_std2a': None, 'taux_reussite_attendu_acad_serie_stmg': None, 'taux_reussite_attendu_acad_serie_sti': None, 'taux_reussite_attendu_acad_serie_stl': None, 'taux_reussite_attendu_acad_serie_st2s': None, 'taux_reussite_attendu_acad_serie_musiq_danse': None, 'taux_reussite_attendu_acad_serie_hotellerie': None, 'taux_reussite_attendu_acad_total_series': None, 'taux_reussite_attendu_france_serie_l': None, 'taux_reussite_attendu_france_serie_es': None, 'taux_reussite_attendu_france_serie_s': None, 'taux_reussite_attendu_france_serie_stg': None, 'taux_reussite_attendu_france_serie_sti2d': None, 'taux_reussite_attendu_france_serie_std2a': None, 'taux_reussite_attendu_france_serie_stmg': None, 'taux_reussite_attendu_france_serie_sti': None, 'taux_reussite_attendu_france_serie_stl': None, 'taux_reussite_attendu_france_serie_st2s': None, 'taux_reussite_attendu_france_serie_musiq_danse': None, 'taux_reussite_attendu_france_serie_hotellerie': None, 'taux_reussite_attendu_france_total_series': None, 'taux_mention_brut_serie_l': None, 'taux_mention_brut_serie_es': None, 'taux_mention_brut_serie_s': None, 'taux_mention_brut_serie_sti2d': None, 'taux_mention_brut_serie_std2a': None, 'taux_mention_brut_serie_stmg': '38', 'taux_mention_brut_serie_stl': None, 'taux_mention_brut_serie_st2s': None, 'taux_mention_brut_serie_musiq_danse': None, 'taux_mention_brut_serie_hotellerie': None, 'taux_mention_brut_toutes_series': 68.0, 'taux_mention_attendu_serie_l': None, 'taux_mention_attendu_serie_es': None, 'taux_mention_attendu_serie_s': None, 'taux_mention_attendu_serie_sti2d': None, 'taux_mention_attendu_serie_std2a': None, 'taux_mention_attendu_serie_stmg': None, 'taux_mention_attendu_serie_stl': None, 'taux_mention_attendu_serie_st2s': None, 'taux_mention_attendu_serie_musiq_danse': None, 'taux_mention_attendu_serie_hotellerie': None, 'taux_mention_attendu_toutes_series': None, 'sructure_pedagogique_en_5_groupes': None, 'sructure_pedagogique_en_7_groupes': None, 'pourcentage_bacheliers_sortants_2de_1re_term_etab': None, 'pourcentage_bacheliers_sortants_terminales_etab': None, 'pourcentage_bacheliers_sortants_2de_1re_term_acad': None, 'pourcentage_bacheliers_sortants_terminales_acad': None, 'pourcentage_bacheliers_sortants_2de_1re_term_france': None, 'pourcentage_bacheliers_sortants_terminales_france': None, 'effectif_de_seconde': 508, 'effectif_de_premiere': 440, 'effectif_de_terminale': 424, 'taux_acces_brut_seconde_bac': 87.0, 'taux_acces_attendu_acad_seconde_bac': None, 'taux_acces_attendu_france_seconde_bac': None, 'taux_acces_brut_premiere_bac': '93', 'taux_acces_attendu_acad_premiere_bac': None, 'taux_acces_attendu_france_premiere_bac': None, 'taux_acces_brut_terminale_bac': '97', 'taux_acces_attendu_france_terminale_bac': None, 'libelle_region_2016': 'AUVERGNE-RHONE-ALPES', 'code_region_2016': '84', 'code_departement': '01', 'libelle_departement': 'Ain', 'va_reu_total': '-2', 'va_acc_seconde': '-1', 'va_men_total': '-6', 'va_reu_l': None, 'va_reu_es': None, 'va_reu_s': None, 'va_reu_stg': None, 'va_reu_sti2d': None, 'va_reu_std2a': None, 'va_reu_stmg': '2', 'va_reu_sti': None, 'va_reu_stl': None, 'va_reu_st2s': None, 'va_reu_musiq_danse': None, 'va_reu_hotellerie': None, 'va_acc_premiere': '-2', 'va_acc_terminale': '-1', 'va_men_l': None, 'va_men_es': None, 'va_men_s': None, 'va_men_sti2d': None, 'va_men_std2a': None, 'va_men_stmg': '-3', 'va_men_stl': None, 'va_men_st2s': None, 'va_men_musiq_danse': None, 'va_men_hotellerie': None, 'presents_gnle': 315.0, 'taux_reu_brut_gnle': '96', 'va_reu_gnle': '-3', 'taux_men_brut_gnle': '74', 'va_men_gnle': '-7', 'nombre_de_mentions_tb_avec_felicitations_g': 3, 'nombre_de_mentions_tb_sans_felicitations_g': 41, 'nombre_de_mentions_b_g': 83, 'nombre_de_mentions_ab_g': 106, 'nombre_de_mentions_tb_avec_felicitations_t': None, 'nombre_de_mentions_tb_sans_felicitations_t': None, 'nombre_de_mentions_b_t': 9, 'nombre_de_mentions_ab_t': 17}, {'etablissement': 'LYCEE PAUL CLAUDEL', 'annee': '2023', 'ville': 'LAON', 'code_etablissement': '0020032Z', 'commune': '02408', 'academie': 'AMIENS', 'departement': 'AISNE', 'secteur_public_pu_prive_pr': 'public', 'effectif_presents_serie_l': None, 'effectif_presents_serie_es': None, 'effectif_presents_serie_s': None, 'effectif_presents_serie_stg': None, 'effectif_presents_serie_sti2d': None, 'effectif_presents_serie_std2a': None, 'effectif_presents_serie_stmg': 63, 'effectif_presents_serie_sti': None, 'effectif_presents_serie_stl': None, 'effectif_presents_serie_st2s': 60, 'effectif_presents_serie_musiq_danse': None, 'effectif_presents_serie_hotellerie': None, 'effectif_presents_total_series': 340, 'taux_brut_de_reussite_serie_l': None, 'taux_brut_de_reussite_serie_es': None, 'taux_brut_de_reussite_serie_s': None, 'taux_brut_de_reussite_serie_stg': None, 'taux_brut_de_reussite_serie_sti2d': None, 'taux_brut_de_reussite_serie_std2a': None, 'taux_brut_de_reussite_serie_stmg': '86', 'taux_brut_de_reussite_serie_sti': None, 'taux_brut_de_reussite_serie_stl': None, 'taux_brut_de_reussite_serie_st2s': '93', 'taux_brut_de_reussite_serie_musiq_danse': None, 'taux_brut_de_reussite_serie_hotellerie': None, 'taux_brut_de_reussite_total_series': 93.0, 'taux_reussite_attendu_acad_serie_l': None, 'taux_reussite_attendu_acad_serie_es': None, 'taux_reussite_attendu_acad_serie_s': None, 'taux_reussite_attendu_acad_serie_stg': None, 'taux_reussite_attendu_acad_serie_sti2d': None, 'taux_reussite_attendu_acad_serie_std2a': None, 'taux_reussite_attendu_acad_serie_stmg': None, 'taux_reussite_attendu_acad_serie_sti': None, 'taux_reussite_attendu_acad_serie_stl': None, 'taux_reussite_attendu_acad_serie_st2s': None, 'taux_reussite_attendu_acad_serie_musiq_danse': None, 'taux_reussite_attendu_acad_serie_hotellerie': None, 'taux_reussite_attendu_acad_total_series': None, 'taux_reussite_attendu_france_serie_l': None, 'taux_reussite_attendu_france_serie_es': None, 'taux_reussite_attendu_france_serie_s': None, 'taux_reussite_attendu_france_serie_stg': None, 'taux_reussite_attendu_france_serie_sti2d': None, 'taux_reussite_attendu_france_serie_std2a': None, 'taux_reussite_attendu_france_serie_stmg': None, 'taux_reussite_attendu_france_serie_sti': None, 'taux_reussite_attendu_france_serie_stl': None, 'taux_reussite_attendu_france_serie_st2s': None, 'taux_reussite_attendu_france_serie_musiq_danse': None, 'taux_reussite_attendu_france_serie_hotellerie': None, 'taux_reussite_attendu_france_total_series': None, 'taux_mention_brut_serie_l': None, 'taux_mention_brut_serie_es': None, 'taux_mention_brut_serie_s': None, 'taux_mention_brut_serie_sti2d': None, 'taux_mention_brut_serie_std2a': None, 'taux_mention_brut_serie_stmg': '38', 'taux_mention_brut_serie_stl': None, 'taux_mention_brut_serie_st2s': '37', 'taux_mention_brut_serie_musiq_danse': None, 'taux_mention_brut_serie_hotellerie': None, 'taux_mention_brut_toutes_series': 57.0, 'taux_mention_attendu_serie_l': None, 'taux_mention_attendu_serie_es': None, 'taux_mention_attendu_serie_s': None, 'taux_mention_attendu_serie_sti2d': None, 'taux_mention_attendu_serie_std2a': None, 'taux_mention_attendu_serie_stmg': None, 'taux_mention_attendu_serie_stl': None, 'taux_mention_attendu_serie_st2s': None, 'taux_mention_attendu_serie_musiq_danse': None, 'taux_mention_attendu_serie_hotellerie': None, 'taux_mention_attendu_toutes_series': None, 'sructure_pedagogique_en_5_groupes': None, 'sructure_pedagogique_en_7_groupes': None, 'pourcentage_bacheliers_sortants_2de_1re_term_etab': None, 'pourcentage_bacheliers_sortants_terminales_etab': None, 'pourcentage_bacheliers_sortants_2de_1re_term_acad': None, 'pourcentage_bacheliers_sortants_terminales_acad': None, 'pourcentage_bacheliers_sortants_2de_1re_term_france': None, 'pourcentage_bacheliers_sortants_terminales_france': None, 'effectif_de_seconde': 339, 'effectif_de_premiere': 375, 'effectif_de_terminale': 356, 'taux_acces_brut_seconde_bac': 87.0, 'taux_acces_attendu_acad_seconde_bac': None, 'taux_acces_attendu_france_seconde_bac': None, 'taux_acces_brut_premiere_bac': '93', 'taux_acces_attendu_acad_premiere_bac': None, 'taux_acces_attendu_france_premiere_bac': None, 'taux_acces_brut_terminale_bac': '96', 'taux_acces_attendu_france_terminale_bac': None, 'libelle_region_2016': 'HAUTS-DE-FRANCE', 'code_region_2016': '32', 'code_departement': '02', 'libelle_departement': 'Aisne', 'va_reu_total': '-1', 'va_acc_seconde': '2', 'va_men_total': '5', 'va_reu_l': None, 'va_reu_es': None, 'va_reu_s': None, 'va_reu_stg': None, 'va_reu_sti2d': None, 'va_reu_std2a': None, 'va_reu_stmg': '-2', 'va_reu_sti': None, 'va_reu_stl': None, 'va_reu_st2s': '2', 'va_reu_musiq_danse': None, 'va_reu_hotellerie': None, 'va_acc_premiere': '1', 'va_acc_terminale': '1', 'va_men_l': None, 'va_men_es': None, 'va_men_s': None, 'va_men_sti2d': None, 'va_men_std2a': None, 'va_men_stmg': '7', 'va_men_stl': None, 'va_men_st2s': '-2', 'va_men_musiq_danse': None, 'va_men_hotellerie': None, 'presents_gnle': 217.0, 'taux_reu_brut_gnle': '95', 'va_reu_gnle': '-1', 'taux_men_brut_gnle': '68', 'va_men_gnle': '7', 'nombre_de_mentions_tb_avec_felicitations_g': 6, 'nombre_de_mentions_tb_sans_felicitations_g': 28, 'nombre_de_mentions_b_g': 47, 'nombre_de_mentions_ab_g': 66, 'nombre_de_mentions_tb_avec_felicitations_t': None, 'nombre_de_mentions_tb_sans_felicitations_t': 1, 'nombre_de_mentions_b_t': 20, 'nombre_de_mentions_ab_t': 25}, {'etablissement': 'LYCEE PIERRE DE LA RAMEE', 'annee': '2023', 'ville': 'SAINT QUENTIN', 'code_etablissement': '0020049T', 'commune': '02691', 'academie': 'AMIENS', 'departement': 'AISNE', 'secteur_public_pu_prive_pr': 'public', 'effectif_presents_serie_l': None, 'effectif_presents_serie_es': None, 'effectif_presents_serie_s': None, 'effectif_presents_serie_stg': None, 'effectif_presents_serie_sti2d': None, 'effectif_presents_serie_std2a': None, 'effectif_presents_serie_stmg': 53, 'effectif_presents_serie_sti': None, 'effectif_presents_serie_stl': None, 'effectif_presents_serie_st2s': 29, 'effectif_presents_serie_musiq_danse': None, 'effectif_presents_serie_hotellerie': None, 'effectif_presents_total_series': 242, 'taux_brut_de_reussite_serie_l': None, 'taux_brut_de_reussite_serie_es': None, 'taux_brut_de_reussite_serie_s': None, 'taux_brut_de_reussite_serie_stg': None, 'taux_brut_de_reussite_serie_sti2d': None, 'taux_brut_de_reussite_serie_std2a': None, 'taux_brut_de_reussite_serie_stmg': '60', 'taux_brut_de_reussite_serie_sti': None, 'taux_brut_de_reussite_serie_stl': None, 'taux_brut_de_reussite_serie_st2s': '86', 'taux_brut_de_reussite_serie_musiq_danse': None, 'taux_brut_de_reussite_serie_hotellerie': None, 'taux_brut_de_reussite_total_series': 85.0, 'taux_reussite_attendu_acad_serie_l': None, 'taux_reussite_attendu_acad_serie_es': None, 'taux_reussite_attendu_acad_serie_s': None, 'taux_reussite_attendu_acad_serie_stg': None, 'taux_reussite_attendu_acad_serie_sti2d': None, 'taux_reussite_attendu_acad_serie_std2a': None, 'taux_reussite_attendu_acad_serie_stmg': None, 'taux_reussite_attendu_acad_serie_sti': None, 'taux_reussite_attendu_acad_serie_stl': None, 'taux_reussite_attendu_acad_serie_st2s': None, 'taux_reussite_attendu_acad_serie_musiq_danse': None, 'taux_reussite_attendu_acad_serie_hotellerie': None, 'taux_reussite_attendu_acad_total_series': None, 'taux_reussite_attendu_france_serie_l': None, 'taux_reussite_attendu_france_serie_es': None, 'taux_reussite_attendu_france_serie_s': None, 'taux_reussite_attendu_france_serie_stg': None, 'taux_reussite_attendu_france_serie_sti2d': None, 'taux_reussite_attendu_france_serie_std2a': None, 'taux_reussite_attendu_france_serie_stmg': None, 'taux_reussite_attendu_france_serie_sti': None, 'taux_reussite_attendu_france_serie_stl': None, 'taux_reussite_attendu_france_serie_st2s': None, 'taux_reussite_attendu_france_serie_musiq_danse': None, 'taux_reussite_attendu_france_serie_hotellerie': None, 'taux_reussite_attendu_france_total_series': None, 'taux_mention_brut_serie_l': None, 'taux_mention_brut_serie_es': None, 'taux_mention_brut_serie_s': None, 'taux_mention_brut_serie_sti2d': None, 'taux_mention_brut_serie_std2a': None, 'taux_mention_brut_serie_stmg': '8', 'taux_mention_brut_serie_stl': None, 'taux_mention_brut_serie_st2s': '34', 'taux_mention_brut_serie_musiq_danse': None, 'taux_mention_brut_serie_hotellerie': None, 'taux_mention_brut_toutes_series': 45.0, 'taux_mention_attendu_serie_l': None, 'taux_mention_attendu_serie_es': None, 'taux_mention_attendu_serie_s': None, 'taux_mention_attendu_serie_sti2d': None, 'taux_mention_attendu_serie_std2a': None, 'taux_mention_attendu_serie_stmg': None, 'taux_mention_attendu_serie_stl': None, 'taux_mention_attendu_serie_st2s': None, 'taux_mention_attendu_serie_musiq_danse': None, 'taux_mention_attendu_serie_hotellerie': None, 'taux_mention_attendu_toutes_series': None, 'sructure_pedagogique_en_5_groupes': None, 'sructure_pedagogique_en_7_groupes': None, 'pourcentage_bacheliers_sortants_2de_1re_term_etab': None, 'pourcentage_bacheliers_sortants_terminales_et

Conversion du dictionnaire lycee ancien vers dataframe panda

In [12]:
df_lycee_ancien = pd.json_normalize(dico_lycee_ancien['results'])
df_lycee_ancien.head()

,etablissement,annee,ville,code_etablissement,commune,academie,departement,secteur_public_pu_prive_pr,effectif_presents_serie_l,effectif_presents_serie_es,...,taux_men_brut_gnle,va_men_gnle,nombre_de_mentions_tb_avec_felicitations_g,nombre_de_mentions_tb_sans_felicitations_g,nombre_de_mentions_b_g,nombre_de_mentions_ab_g,nombre_de_mentions_tb_avec_felicitations_t,nombre_de_mentions_tb_sans_felicitations_t,nombre_de_mentions_b_t,nombre_de_mentions_ab_t
0,LYCEE PAUL PAINLEVE (GENERAL ET TECHNO.),2023,OYONNAX,0010034G,01283,LYON,AIN,public,None,None,...,48,-8,NaN,6.0,9.0,17.0,None,1.0,6.0,21.0
1,LYCEE DE LA COTIERE,2023,LA BOISSE,0011326L,01049,LYON,AIN,public,None,None,...,74,-7,3.0,41.0,83.0,106.0,None,NaN,9.0,17.0
2,LYCEE PAUL CLAUDEL,2023,LAON,0020032Z,02408,AMIENS,AISNE,public,None,None,...,68,7,6.0,28.0,47.0,66.0,None,1.0,20.0,25.0
3,LYCEE PIERRE DE LA RAMEE,2023,SAINT QUENTIN,0020049T,02691,AMIENS,AISNE,public,None,None,...,59,-1,2.0,11.0,29.0,52.0,None,1.0,6.0,7.0
4,LYCEE SAINT CHARLES,2023,CHAUNY,0021870X,02173,AMIENS,AISNE,privé sous contrat,None,None,...,70,9,NaN,1.0,6.0,7.0,None,NaN,NaN,NaN

In [13]:
df_lycee_ancien.describe()

,effectif_presents_serie_sti2d,effectif_presents_serie_std2a,effectif_presents_serie_stmg,effectif_presents_serie_stl,effectif_presents_serie_st2s,effectif_presents_total_series,taux_brut_de_reussite_total_series,taux_mention_brut_toutes_series,effectif_de_seconde,effectif_de_premiere,effectif_de_terminale,taux_acces_brut_seconde_bac,presents_gnle,nombre_de_mentions_tb_avec_felicitations_g,nombre_de_mentions_tb_sans_felicitations_g,nombre_de_mentions_b_g,nombre_de_mentions_ab_g,nombre_de_mentions_tb_sans_felicitations_t,nombre_de_mentions_b_t,nombre_de_mentions_ab_t
count,4.000000,1.0,11.000000,3.000000,6.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,18.000000,13.000000,18.000000,18.000000,18.000000,11.000000,15.000000,15.000000
mean,27.750000,34.0,61.545455,20.666667,38.333333,211.800000,95.350000,61.900000,253.100000,231.75000,228.800000,81.250000,173.444444,3.615385,22.333333,38.944444,51.166667,1.818182,10.200000,19.933333
std,7.632169,NaN,28.306761,4.509250,12.628011,142.136924,3.842628,15.168874,180.242497,158.87992,147.737534,7.826238,109.771539,2.567050,15.792776,25.039903,31.923161,1.537412,4.178175,8.514414
min,19.000000,34.0,16.000000,16.000000,28.000000,20.000000,85.000000,37.000000,18.000000,30.00000,22.000000,58.000000,20.000000,1.000000,1.000000,6.000000,7.000000,1.000000,5.000000,7.000000
25%,23.500000,34.0,41.500000,18.500000,29.750000,90.750000,93.750000,50.250000,114.500000,88.75000,106.250000,77.750000,96.250000,2.000000,11.250000,24.750000,27.500000,1.000000,7.000000,15.500000
50%,27.500000,34.0,63.000000,21.000000,33.000000,177.000000,96.000000,63.500000,216.000000,205.50000,210.500000,82.000000,152.000000,3.000000,24.500000,31.500000,42.000000,1.000000,9.000000,17.000000
75%,31.750000,34.0,81.000000,23.000000,43.750000,322.500000,98.000000,69.250000,357.500000,360.75000,350.000000,87.000000,231.250000,4.000000,28.750000,58.250000,64.750000,2.000000,11.500000,23.500000
max,37.000000,34.0,105.000000,25.000000,60.000000,504.000000,100.000000,89.000000,620.000000,546.00000,504.000000,91.000000,410.000000,11.000000,64.000000,93.000000,106.000000,6.000000,20.000000,37.000000

In [19]:
df_lycee_ancien['annee'].dtype

dtype('O')

In [21]:
df_lycee_ancien['annee'] = df_lycee_ancien['annee'].astype(int)
df_lycee_ancien['annee'].dtype

dtype('int64')

In [22]:
df_lycee_ancien.describe()

,annee,effectif_presents_serie_sti2d,effectif_presents_serie_std2a,effectif_presents_serie_stmg,effectif_presents_serie_stl,effectif_presents_serie_st2s,effectif_presents_total_series,taux_brut_de_reussite_total_series,taux_mention_brut_toutes_series,effectif_de_seconde,...,effectif_de_terminale,taux_acces_brut_seconde_bac,presents_gnle,nombre_de_mentions_tb_avec_felicitations_g,nombre_de_mentions_tb_sans_felicitations_g,nombre_de_mentions_b_g,nombre_de_mentions_ab_g,nombre_de_mentions_tb_sans_felicitations_t,nombre_de_mentions_b_t,nombre_de_mentions_ab_t
count,20.0,4.000000,1.0,11.000000,3.000000,6.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.000000,18.000000,13.000000,18.000000,18.000000,18.000000,11.000000,15.000000,15.000000
mean,2023.0,27.750000,34.0,61.545455,20.666667,38.333333,211.800000,95.350000,61.900000,253.100000,...,228.800000,81.250000,173.444444,3.615385,22.333333,38.944444,51.166667,1.818182,10.200000,19.933333
std,0.0,7.632169,NaN,28.306761,4.509250,12.628011,142.136924,3.842628,15.168874,180.242497,...,147.737534,7.826238,109.771539,2.567050,15.792776,25.039903,31.923161,1.537412,4.178175,8.514414
min,2023.0,19.000000,34.0,16.000000,16.000000,28.000000,20.000000,85.000000,37.000000,18.000000,...,22.000000,58.000000,20.000000,1.000000,1.000000,6.000000,7.000000,1.000000,5.000000,7.000000
25%,2023.0,23.500000,34.0,41.500000,18.500000,29.750000,90.750000,93.750000,50.250000,114.500000,...,106.250000,77.750000,96.250000,2.000000,11.250000,24.750000,27.500000,1.000000,7.000000,15.500000
50%,2023.0,27.500000,34.0,63.000000,21.000000,33.000000,177.000000,96.000000,63.500000,216.000000,...,210.500000,82.000000,152.000000,3.000000,24.500000,31.500000,42.000000,1.000000,9.000000,17.000000
75%,2023.0,31.750000,34.0,81.000000,23.000000,43.750000,322.500000,98.000000,69.250000,357.500000,...,350.000000,87.000000,231.250000,4.000000,28.750000,58.250000,64.750000,2.000000,11.500000,23.500000
max,2023.0,37.000000,34.0,105.000000,25.000000,60.000000,504.000000,100.000000,89.000000,620.000000,...,504.000000,91.000000,410.000000,11.000000,64.000000,93.000000,106.000000,6.000000,20.000000,37.000000

In [25]:
df_lycee_ancien.shape

(20, 145)